[package]
name = "bridged_keystore"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.4.2", features = ["full"] }
alloy-consensus = "0.4.2"
alloy-rlp = "0.3.8"
tokio = { version = "1.40.0", features = ["full"] }
